---
# tasks for ansible-disable-selinux
- name: Remove
  shell: rm -f /var/run/yum.pid
- name: Install libselinux as prerequisite for SELinux Ansible module
  yum:
    name: "{{item}}"
    state: latest
    lock_timeout: 180
  with_items:
    - libselinux-python
    - libsemanage-python

- name: Disable SELinux at next reboot
  selinux:
    state: disabled
  register: task_result

- name: Rebooting server
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: task_result is changed

- name: Wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: task_result is changed

    #- name: Set SELinux in permissive mode until the machine is rebooted
  # command: setenforce 0
    # ignore_errors: true
    #  changed_when: false

- name: Print
  shell: echo "Hello"

- name: Install python3
  shell: yum install -y python3

- name: Check Python Version
  shell: python3 --version

